import { PortType } from '../../src/generated/prisma/client';

export const ports = [
  // ===== SEAPORTS =====
  {
    code: "SGSIN",
    name: "Port of Singapore",
    type: PortType.SEA,
    countryCode: "SG",
    lat: 1.264,
    lng: 103.840,
  },
  {
    code: "CNSHA",
    name: "Port of Shanghai",
    type: PortType.SEA,
    countryCode: "CN",
    lat: 31.230,
    lng: 121.490,
  },
  {
    code: "NLRTM",
    name: "Port of Rotterdam",
    type: PortType.SEA,
    countryCode: "NL",
    lat: 51.948,
    lng: 4.138,
  },
  {
    code: "USLAX",
    name: "Port of Los Angeles",
    type: PortType.SEA,
    countryCode: "US",
    lat: 33.740,
    lng: -118.270,
  },
  {
    code: "AEDXB",
    name: "Jebel Ali Port",
    type: PortType.SEA,
    countryCode: "AE",
    lat: 25.011,
    lng: 55.061,
  },
  {
    code: "NGLOS",
    name: "Apapa Port",
    type: PortType.SEA,
    countryCode: "NG",
    lat: 6.448,
    lng: 3.367,
  },
  {
    code: "DEHAM",
    name: "Port of Hamburg",
    type: PortType.SEA,
    countryCode: "DE",
    lat: 53.540,
    lng: 9.960,
  },
  {
    code: "BEANR",
    name: "Port of Antwerp",
    type: PortType.SEA,
    countryCode: "BE",
    lat: 51.260,
    lng: 4.400,
  },
  {
    code: "HKHKG",
    name: "Port of Hong Kong",
    type: PortType.SEA,
    countryCode: "HK",
    lat: 22.307,
    lng: 114.177,
  },
  {
    code: "BRSSZ",
    name: "Port of Santos",
    type: PortType.SEA,
    countryCode: "BR",
    lat: -23.960,
    lng: -46.328,
  },

  // ===== AIRPORTS =====

  {
    code: "LHR",
    name: "London Heathrow Airport",
    type: PortType.AIR,
    countryCode: "GB",
    lat: 51.470,
    lng: -0.454,
  },
  {
    code: "JFK",
    name: "John F. Kennedy International Airport",
    type: PortType.AIR,
    countryCode: "US",
    lat: 40.641,
    lng: -73.778,
  },
  {
    code: "DXB",
    name: "Dubai International Airport",
    type: PortType.AIR,
    countryCode: "AE",
    lat: 25.253,
    lng: 55.365,
  },
  {
    code: "SIN",
    name: "Singapore Changi Airport",
    type: PortType.AIR,
    countryCode: "SG",
    lat: 1.364,
    lng: 103.991,
  },
  {
    code: "LOS",
    name: "Murtala Muhammed International Airport",
    type: PortType.AIR,
    countryCode: "NG",
    lat: 6.577,
    lng: 3.321,
  },
  {
    code: "CDG",
    name: "Charles de Gaulle Airport",
    type: PortType.AIR,
    countryCode: "FR",
    lat: 49.009,
    lng: 2.547,
  },
  {
    code: "AMS",
    name: "Amsterdam Schiphol Airport",
    type: PortType.AIR,
    countryCode: "NL",
    lat: 52.310,
    lng: 4.768,
  },
  {
    code: "FRA",
    name: "Frankfurt Airport",
    type: PortType.AIR,
    countryCode: "DE",
    lat: 50.037,
    lng: 8.562,
  },
  {
    code: "NRT",
    name: "Narita International Airport",
    type: PortType.AIR,
    countryCode: "JP",
    lat: 35.772,
    lng: 140.392,
  },
  {
    code: "SYD",
    name: "Sydney Kingsford Smith Airport",
    type: PortType.AIR,
    countryCode: "AU",
    lat: -33.939,
    lng: 151.175,
  },

  // ===== LAND PORTS =====

  {
    code: "NGSEM",
    name: "Seme Border",
    type: PortType.LAND,
    countryCode: "NG",
    lat: 6.357,
    lng: 2.823,
  },
  {
    code: "USMEX",
    name: "Laredo Border Crossing",
    type: PortType.LAND,
    countryCode: "US",
    lat: 27.506,
    lng: -99.507,
  },
  {
    code: "INWAG",
    name: "Wagah Border",
    type: PortType.LAND,
    countryCode: "IN",
    lat: 31.604,
    lng: 74.573,
  },
  {
    code: "ZABEI",
    name: "Beitbridge Border Post",
    type: PortType.LAND,
    countryCode: "ZA",
    lat: -22.216,
    lng: 30.000,
  },
  {
    code: "USCAN",
    name: "Peace Bridge Crossing",
    type: PortType.LAND,
    countryCode: "US",
    lat: 42.905,
    lng: -78.905,
  },
];